WebShop/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using WebShop.Logic;
using WebShop.Models;

namespace WebShop.Controllers
{
    public class CategoryController : Controller
    {
        public IActionResult List()
        {
            if(!HttpContext.Session.GetIsAdmin())
            {
                // return RedirectToAction("Index", "Home");  <- atgriežuz sākumlapu
                return NotFound();
            }

            var categories = CategoryManager.GetAll().Select(c => c.ToModel()).ToList();
            return View(categories);
        }

        [HttpGet]
        public IActionResult Create()
        {
            if (!HttpContext.Session.GetIsAdmin())
            {
                return NotFound();
            }

            var model = new CategoryModel();
            return View(model);
        }

        [HttpPost]
        public IActionResult Create(CategoryModel model)
        {
            if (ModelState.IsValid)
            {
                if (model.ParentId.HasValue)
                {
                    var category = CategoryManager.Get(model.ParentId.Value);

                    if (category == null)
                    {
                        ModelState.AddModelError("cat", "Category not found!");

                        return View(model);
                    }
                }

                CategoryManager.Create(model.Name, model.ParentId);

                return RedirectToAction(nameof(List));
            }

            return View(model);
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
           if (!HttpContext.Session.GetIsAdmin())
            {
                return NotFound();
            }

            CategoryManager.Delete(id);
            return RedirectToAction(nameof(List));
        }
    }
}

WebShop/Controllers/ItemController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using WebShop.Logic;
using WebShop.Models;

namespace WebShop.Controllers
{
    public class ItemController : Controller
    {
        public IActionResult Index(int id)
        {
            // id -> kategorijas ID

            var model = new HomeModel();
            model.Categories = CategoryManager.GetAll().Select(c => c.ToModel()).ToList();

            //  preču atlase no DB pēc kategorijas id, izm. ItemManager

            model.Items = ItemManager.GetByCategory(id).Select(i => i.ToModel()).ToList();

            foreach (var cat in model.Categories)
            {
                cat.ItemCount = CategoryManager.GetItemCount(cat.Id);
            }

            return View(model);
        }

        public IActionResult List()
        {
           if (!HttpContext.Session.GetIsAdmin())
            {
                return NotFound();
            }

            var items = ItemManager.GetAll().Select(c => c.ToModel()).ToList();
            return View(items);
        }

        [HttpGet]
        public IActionResult Create()
        {
            if (!HttpContext.Session.GetIsAdmin())
            {
                return NotFound();
            }

            var model = new ItemModel();
            return View(model);
        }

        [HttpPost]
        public IActionResult Create(ItemModel model)
        {
            if (ModelState.IsValid)
            {
                var category = CategoryManager.Get(model.CategoryId);

                if (category == null)
                {
                    ModelState.AddModelError("cat", "Category not found!");
                }
                else
                {
                    ItemManager.Create(category.Id, model.Name, model.Description, model.Price);

                    return RedirectToAction(nameof(List));
                }
            }

            return View(model);
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            if (!HttpContext.Session.GetIsAdmin())
            {
                return NotFound();
            }

            ItemManager.Delete(id);
            return RedirectToAction(nameof(List));
        }

        [HttpGet]
        public IActionResult Buy(int id)
        {
            // jāsaglabā izvēlētā prece lietotāja grozā.

            UserCartManager.Create(HttpContext.Session.GetUserId(), id);
            return RedirectToAction("MyCart", "Account");
        }
    }
}

WebShop/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebShop</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Web shop</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    @if (Context.Session.GetIsAdmin())
                    {
                        <li><a asp-controller="Category" asp-action="List">Manage categories</a></li>
                        <li><a asp-controller="Item" asp-action="List">Manage items</a></li>
                    }
                    @if (Context.Session.GetUserName() == null)
                    {
                        <li><a asp-controller="Account" asp-action="SignUp">Sign up</a></li>
                        <li><a asp-controller="Account" asp-action="SignIn">Sign in</a></li>
                    }
                    else
                    {
                        <li><a asp-controller="Account" asp-action="MyCart">My cart</a></li>
                        <li><a href="#">Hello, @Context.Session.GetUserName()</a></li>
                        <li><a asp-controller="Account" asp-action="SignOut">Sign out</a></li>

                    }
                </ul>
            </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container">
        @RenderBody()
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>