WebApp/Models/CategoriesModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace WebApp.Models
{
    public class CategoriesModel
    {
        public int Id { get; set; }

        [Required]
        [DataType(DataType.Text)]
        [StringLength(50)]
        [Display(Name = "Name: ")]
        public string Name { get; set; }
    }
}

WebApp/Models/ErrorViewModel.cs
using System;

namespace WebApp.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

WebApp/Models/GoodsModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace WebApp.Models
{
    public class GoodsModel
    {
        public int Id { get; set; }

        [Required]
        [DataType(DataType.Text)]
        [StringLength(50)]
        [Display(Name = "Name: ")]
        public string GoodsName { get; set; }

        [DataType(DataType.Text)]
        [StringLength(500)]
        [Display(Name = "Description: ")]
        public string Description { get; set; }

        [Required]
        [Display(Name = "Price: ")]
        public decimal Price { get; set; }

        [DataType(DataType.Text)]
        [StringLength(150)]
        [Display(Name = "Location: ")]
        public string Location { get; set; }

        [Required]
        [DataType(DataType.Text)]
        [StringLength(20)]
        [Display(Name = "Category: ")]
        public string CategoryName { get; set; }

        public CategoriesModel Categories { get; set; }
    }
}

WebApp/Controllers/CategoriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using WebApp.Logic;
using WebApp.Models;

namespace WebApp.Controllers
{
    public class CategoriesController : Controller
    {
        public IActionResult Index()
        {
                var categories = CategoryManager.GetAllCategories().Select(c => c.ToModel()).ToList();

                return View(categories);
        }

        // lietotāja meklēšana
        public IActionResult ViewCat(int id)
        {
                var category = CategoryManager.GetCategory(id).ToModel();

                return View(category);
        }

        [HttpGet]
        public IActionResult AddCat()
        {
            var category = new CategoriesModel();

            return View(category);
        }

        [HttpPost]
        public IActionResult AddCat(CategoriesModel model)
        {
            // pārbauda vai ir ievadīti derīgi dati
            if (ModelState.IsValid)
            {
                // VISS OK - modelis ir derīgs, var veikt datu saglabāšanu
                // insert into Users(Email, Phone, Name)
                // values(@email, @phone, @name)
                // COMMIT;

                CategoryManager.CreateNewCategory(model.Name);

                    // aizsūtam viņu atpakaļ uz user list
                    return RedirectToAction(nameof(Index));
            }

            return View(model);
        }
    }
}

WebApp/Controllers/GoodsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.ValueGeneration;
using WebApp.Logic;
using WebApp.Models;

namespace WebApp.Controllers
{
    public class GoodsController : Controller
    {
        // id -> kategorijas ID
        // (int? id) -> ID var nebūt definēts, ? ir nullējams
        public IActionResult Index()
        {
                var items = ItemManager.GetAllItems().Select(i => i.ToModel()).ToList();

               return View(items);
        }

        // id -> preces ID
        public IActionResult ViewGoods(int id)
        {
            var item = ItemManager.GetItem(id).ToModel();
               
                return View(item);
        }

        [HttpGet]
        public IActionResult Create()
        {
            var model = new GoodsModel();

            return View(model);
        }

        [HttpPost]
        public IActionResult Create(GoodsModel model)
        {
            if (ModelState.IsValid)
            {
                ItemManager.CreateNewItem(model.GoodsName, model.Price, model.Description, model.Location);
                           
                        return RedirectToAction(nameof(Index));
            }
            
            return View(model);
        }
    }
}

WebApp/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using WebApp.Models;

namespace WebApp.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

WebApp/Views/Categories/AddCat.cshtml
@model CategoriesModel
@{
    ViewData["Title"] = "Add New Category";
}

<h2>Add new category</h2>

@Html.ValidationSummary()

<form class="form-horizontal" asp-controller="Categories" asp-action="AddCat" method="post">
    <div class="form-group">
        <label asp-for="Name" class="col-sm-2 control-label"></label>
        <div class="col-sm-10">
            <input class="form-control" asp-for="Name">
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="btn btn-default">Save</button>
        </div>
    </div>
</form>

WebApp/Views/Categories/Index.cshtml
@model List<CategoriesModel>
@{
    ViewData["Title"] = "Categories";
}

<h2>All categories</h2>

<table class="table table-striped">
    <tr>
        <th>#</th>
        <th>Name</th>
        <th></th>
    </tr>
    @foreach(var category in Model)
    {
        <tr>
            <td>@category.Id</td>
            <td>@category.Name</td>
            <td><a asp-controller="Goods" asp-action="Index" asp-route-id="@category.Id">View</a></td>
       </tr>
    }
</table>

WebApp/Views/Categories/ViewCat.cshtml
@model CategoriesModel
@{
    ViewData["Title"] = "View Category";
}

<h2>@Model.Name</h2>

<a asp-controller="Categories" asp-action="Index" asp-route-id="@Model.Id">Back</a>
<br />

WebApp/Views/Goods/Create.cshtml
@model GoodsModel
@{
    ViewData["Title"] = "Create New Item";
}

    <h2>Create New Item</h2>

@Html.ValidationSummary()

<form class="form-horizontal" asp-controller="Goods" asp-action="Create" method="post">
    <div class="form-group">
        <label asp-for="GoodsName" class="col-sm-2 control-label"></label>
        <div class="col-sm-10">
            <input class="form-control" asp-for="GoodsName">
        </div>
    </div>
    <div class="form-group">
        <label asp-for="Price" class="col-sm-2 control-label"></label>
        <div class="col-sm-10">
            <input class="form-control" asp-for="Price">
        </div>
    </div>
    <div class="form-group">
        <label asp-for="Description" class="col-sm-2 control-label"></label>
        <div class="col-sm-10">
            <input class="form-control" asp-for="Description">
        </div>
    </div>
    <div class="form-group">
        <label asp-for="Location" class="col-sm-2 control-label"></label>
        <div class="col-sm-10">
            <input class="form-control" asp-for="Location">
        </div>
    </div>
    <div class="form-group">
        <label asp-for="CategoryName" class="col-sm-2 control-label"></label>
        <div class="col-sm-10">
            <input class="form-control" asp-for="CategoryName">
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="btn btn-default">Save</button>
        </div>
    </div>
</form>

WebApp/Views/Goods/Index.cshtml
@model List<GoodsModel>
@{
    ViewData["Title"] = "Goods";
}

<h2>All goods</h2>

<a asp-controller="Categories" asp-action="Index" asp-route-id="">Back</a>
<br />

@if (Model.Count > 0)
{
<table class="table table-striped">
    <tr>
        <th>Price</th>
        <th>Name</th>
        <th>Description</th>
        <th></th>
    </tr>
    @foreach (var goods in Model)
    {
        <tr>
            <td>@goods.Price</td>
            <td>@goods.GoodsName</td>
            <td>@goods.Description</td>
            <td><a asp-controller="Goods" asp-action="ViewGoods" asp-route-id="@goods.Id">View</a></td>
        </tr>
    }
</table>
}
else
{
    <div>Nav preču!</div>
}

WebApp/Views/Goods/ViewGoods.cshtml
@model GoodsModel
@{
    ViewData["Title"] = "View Item";
}

    <h2>@Model.GoodsName</h2>

<div>
    Name: @Model.GoodsName
</div>
<div>
    Category: @Model.CategoryName
</div>
<div>
    Description: @Model.Description
</div>
<div>
    Price: @Model.Price
</div>
<div>
    Location: @Model.Location
</div>
<div>
    <a asp-controller="Categories" asp-action="Index" asp-route-id="@Model.Id">Back</a>
</div>

WebApp/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

WebApp/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

WebApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

    <h2>Welcome to my Web catalog!</h2>

WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApp</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">WebApp</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Categories" asp-action="Index">Categories</a></li>
                    <li><a asp-area="" asp-controller="Goods" asp-action="Index">Goods</a></li>
                    <li><a asp-area="" asp-controller="Categories" asp-action="AddCat">Create category</a></li>
                    <li><a asp-area="" asp-controller="Goods" asp-action="Create">Create item</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2020 - WebApp</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>